import globals from 'globals';
import noUnsanitized from 'eslint-plugin-no-unsanitized';

// ESLint for the two SPAs, the shared package and the repo's Node tooling
// (37b stage 6). It replaces the `node --check` loop CI used to run: that
// checked one property, "does this file parse", on a fixed list of paths. The
// build already fails on a parse error inside the module graph, so what is left
// to check is everything the graph does not reach — the classic scripts, the
// unit-test layer, the .mjs guards — plus the errors a parser cannot see.
//
// Deliberately a small rule set. This is a plain-DOM codebase with a settled
// style; a large preset would spend its first day rewriting working code and
// its second being disabled. Three rules earn their place:
//
//   no-undef       — the one that pays for the whole file. Under classic
//                    scripts every export landed on `window`, so a missing
//                    dependency still resolved at runtime; under ES modules a
//                    forgotten `import` is a ReferenceError the build does not
//                    catch (an unimported free identifier is just a global
//                    read). 37b stage 3 hit exactly that when a stray
//                    `git checkout` reverted one file's imports.
//   no-unused-vars — catches the other half of an incomplete refactor: the
//                    import that outlived its last caller.
//   no-unsanitized — see the HTML-safety block below.
export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/dist-standalone/**',
      'octbase-api/**',
      'pgdata_dev/**',
      '**/.venv/**',
      // Vendored third-party code: reviewed and SHA-256-pinned in
      // scripts/vendor-manifest.txt, not ours to restyle. Linting it would
      // report upstream's choices as our findings.
      'octbase-shared/purify.js',
      'octbase-shared/qrcode.js',
      'scripts/vendor/**',
      // Generated by the Vite build, not authored.
      'octbase-frontend/vendor/**',
    ],
  },

  // ── The SPA module graph + the shared package ──────────────────────────────
  {
    files: ['octbase-frontend/js/**/*.js', 'octbase-mobile/js/**/*.js', 'octbase-shared/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      // Browser globals only. `DOMPurify` and `qrcode` were declared here as
      // ambient readonly globals while they were vendored UMD files loaded by
      // a <script> tag; 37b stage 4 made them npm imports, so declaring them
      // would now do the opposite of its job — it would tell `no-undef` to
      // accept a bare `DOMPurify` that resolves to nothing at runtime.
      globals: { ...globals.browser },
    },
    plugins: { 'no-unsanitized': noUnsanitized },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],

      // ── HTML safety ────────────────────────────────────────────────────────
      // The codebase renders through `innerHTML`, which is safe only because
      // every dynamic value passes an escaping producer first (js/README.md,
      // "HTML-safety convention"). 37b's brief says to add this plugin and keep
      // the bespoke guard "until the ESLint rule demonstrably covers its cases,
      // then decide". Measured 2026-07-31, and the two rules landed in opposite
      // places — so they are configured differently rather than as a pair.
      //
      // `method` — ENABLED, and it earns it: it covers `insertAdjacentHTML`,
      // which scripts/check-innerhtml.mjs does NOT (its sink regex is
      // innerHTML/outerHTML assignment plus document.write). One call site
      // exists; `contentToolbar` is named below as a producer, the same trust
      // the bespoke guard extends to every fooHtml()/fooInner() helper.
      'no-unsanitized/method': ['error', {
        escape: {
          taggedTemplates: ['html'],
          methods: ['esc', 'sanitizeRichText', 'icon', 'contentToolbar'],
        },
      }],

      // `property` — OFF, on the evidence. Enabling it reports **104 findings,
      // none of them a violation of this codebase's convention**: 62 are
      // untagged template literals in files the html`` migration has not
      // reached yet (scripts/check-innerhtml.mjs tracks exactly those, by name,
      // in its STRICT_FILES ratchet), and the other ~42 assign the return value
      // of a producer function or a variable holding one — which the plugin
      // cannot trace and no `escape.methods` list can fix, because the escaping
      // happened one call deeper.
      //
      // Re-measure with: `npx eslint . --rule '{"no-unsanitized/property":"error"}'`
      // The condition for switching this on is not "someone feels ready": it is
      // the html`` ratchet reaching every file that writes innerHTML, at which
      // point the 62 disappear and the rest can be judged on their own. Until
      // then the bespoke guard is the one that understands the convention, and
      // this rule would only train people to ignore ESLint output.
      'no-unsanitized/property': 'off',
    },
  },

  // ── Classic scripts: outside the module graph on purpose ───────────────────
  // theme-init.js runs before first paint (CSP/FOUC constraint) and the other
  // three are one <script> each on a static page. They are parsed as scripts,
  // not modules, which is what they are.
  {
    files: [
      'octbase-frontend/js/theme-init.js',
      'octbase-frontend/js/docs-init.js',
      'octbase-frontend/js/user-guide-nav.js',
      'octbase-mobile/js/theme-init.js',
    ],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: { ...globals.browser, SwaggerUIBundle: 'readonly' },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
    },
  },

  // ── The unit-test layer and its harness ────────────────────────────────────
  // Both global sets, deliberately: these files run under Vitest in Node, but
  // the ones that declare `// @vitest-environment jsdom` legitimately use
  // `document` and `localStorage`. (They would inherit the browser set anyway
  // from the SPA block above, which also matches `js/*.test.js` — saying it
  // here means the next reader does not have to work that out from flat
  // config's merge order.)
  {
    files: ['octbase-frontend/js/*.test.js', 'octbase-frontend/js/testutil.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node, ...globals.browser },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
    },
  },

  // ── Repo tooling: the guards and the Vite configs ──────────────────────────
  {
    files: ['scripts/**/*.mjs', '*.config.mjs', 'octbase-*/vite*.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      // The Vite configs are ESM but use __dirname, which Vite provides.
      globals: { ...globals.node, __dirname: 'readonly' },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
    },
  },
];
