package docs_test

import (
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/octbase/octbase-api/internal/testutil"
)

func mustCreatePageID(t *testing.T, srv *httptest.Server, projectID, title, content string) string {
	t.Helper()
	body := map[string]string{"title": title}
	if content != "" {
		body["content"] = content
	}
	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+projectID+"/pages", body, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusCreated)
	var page map[string]interface{}
	testutil.DecodeJSON(t, resp, &page)
	return page["id"].(string)
}

func TestCreatePage_OK(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Getting Started", "content": "= Getting Started\n\nWelcome."}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusCreated)

	var page map[string]interface{}
	testutil.DecodeJSON(t, resp, &page)
	if page["title"] != "Getting Started" {
		t.Errorf("title = %v", page["title"])
	}
	if page["status"] != "DRAFT" {
		t.Errorf("status = %v, want DRAFT", page["status"])
	}
	if page["slug"] == "" {
		t.Error("slug should not be empty")
	}
	if renderedHTML, ok := page["renderedHtml"].(string); !ok || !strings.Contains(renderedHTML, "<h1") {
		t.Errorf("renderedHtml should contain heading, got: %v", page["renderedHtml"])
	}
}

func TestCreatePage_SlugAutoGenerated(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "My New Page"}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusCreated)
	var page map[string]interface{}
	testutil.DecodeJSON(t, resp, &page)
	if page["slug"] != "my-new-page" {
		t.Errorf("slug = %v, want my-new-page", page["slug"])
	}
}

func TestCreatePage_DuplicateSlug(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Duplicate", "slug": "my-slug"}, testutil.DemoUserID)

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Another", "slug": "my-slug"}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusConflict)
	var e map[string]interface{}
	testutil.DecodeJSON(t, resp, &e)
	if e["code"] != "SLUG_CONFLICT" {
		t.Errorf("code = %v, want SLUG_CONFLICT", e["code"])
	}
}

func TestListPages(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Page A", "slug": "a"}, testutil.DemoUserID)
	testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Page B", "slug": "b"}, testutil.DemoUserID)

	resp := testutil.Do(t, srv, http.MethodGet, "/api/v1/projects/"+pid+"/pages", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var pages []interface{}
	testutil.DecodeJSON(t, resp, &pages)
	if len(pages) != 2 {
		t.Errorf("expected 2 pages, got %d", len(pages))
	}
}

func TestGetPage_Found(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	createResp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "My Page"}, testutil.DemoUserID)
	testutil.AssertStatus(t, createResp, http.StatusCreated)
	var created map[string]interface{}
	testutil.DecodeJSON(t, createResp, &created)
	pageID := created["id"].(string)

	resp := testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/"+pageID, nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var page map[string]interface{}
	testutil.DecodeJSON(t, resp, &page)
	if page["id"] != pageID {
		t.Errorf("id = %v, want %v", page["id"], pageID)
	}
}

func TestGetPage_NotFound(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)

	resp := testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/00000000-0000-0000-0000-000000000000", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusNotFound)
}

func TestUpdatePage_OK(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Old Title"}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	resp := testutil.Do(t, srv, http.MethodPatch, "/api/v1/pages/"+pageID,
		map[string]string{"title": "New Title", "content": "= New Title\n\nNew body."}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var updated map[string]interface{}
	testutil.DecodeJSON(t, resp, &updated)
	if updated["title"] != "New Title" {
		t.Errorf("title = %v, want New Title", updated["title"])
	}
	if renderedHTML, ok := updated["renderedHtml"].(string); !ok || !strings.Contains(renderedHTML, "New Title") {
		t.Errorf("renderedHtml should be updated, got: %v", updated["renderedHtml"])
	}
}

func TestUpdatePage_BlockedWhenArchived(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Will Archive"}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/archive", nil, testutil.DemoUserID)

	resp := testutil.Do(t, srv, http.MethodPatch, "/api/v1/pages/"+pageID,
		map[string]string{"title": "Should Fail"}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusUnprocessableEntity)
	var e map[string]interface{}
	testutil.DecodeJSON(t, resp, &e)
	if e["code"] != "PAGE_ARCHIVED" {
		t.Errorf("code = %v, want PAGE_ARCHIVED", e["code"])
	}
}

func TestRenderPreview_DoesNotModifyPage(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Static", "content": "= Static\n\nOriginal."}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/render-preview",
		map[string]string{"content": "= Preview\n\nDifferent content."}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var result map[string]interface{}
	testutil.DecodeJSON(t, resp, &result)
	if _, ok := result["html"]; !ok {
		t.Error("response should have 'html' key")
	}

	// Verify the page was not modified
	getResp := testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/"+pageID, nil, testutil.DemoUserID)
	var page map[string]interface{}
	testutil.DecodeJSON(t, getResp, &page)
	if page["content"] != "= Static\n\nOriginal." {
		t.Errorf("page content was modified: %v", page["content"])
	}
}

func TestPublishPage_CreatesRevision(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Publishable", "content": "= Publishable\n\nContent."}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/publish",
		map[string]string{"message": "First release"}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var published map[string]interface{}
	testutil.DecodeJSON(t, resp, &published)
	if published["status"] != "PUBLISHED" {
		t.Errorf("status = %v, want PUBLISHED", published["status"])
	}

	revResp := testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/"+pageID+"/revisions", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, revResp, http.StatusOK)
	var revs []interface{}
	testutil.DecodeJSON(t, revResp, &revs)
	if len(revs) != 1 {
		t.Errorf("expected 1 revision, got %d", len(revs))
	}
}

func TestArchivePage(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Will Archive"}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/archive", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var archived map[string]interface{}
	testutil.DecodeJSON(t, resp, &archived)
	if archived["status"] != "ARCHIVED" {
		t.Errorf("status = %v, want ARCHIVED", archived["status"])
	}
}

func TestSearchPages(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Deployment Guide", "slug": "deploy"}, testutil.DemoUserID)
	testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "API Reference", "slug": "api-ref"}, testutil.DemoUserID)

	resp := testutil.Do(t, srv, http.MethodGet,
		"/api/v1/projects/"+pid+"/search/pages?q=deploy", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var pages []map[string]interface{}
	testutil.DecodeJSON(t, resp, &pages)
	if len(pages) == 0 {
		t.Error("expected results for 'deploy'")
	}
}

func TestSearchPages_QueryTooLong(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	resp := testutil.Do(t, srv, http.MethodGet,
		"/api/v1/projects/"+pid+"/search/pages?q="+strings.Repeat("a", 501), nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusBadRequest)
	var e map[string]interface{}
	testutil.DecodeJSON(t, resp, &e)
	if e["code"] != "QUERY_TOO_LONG" {
		t.Errorf("code = %v, want QUERY_TOO_LONG", e["code"])
	}
}

func TestPageReferences_Rebuild(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	tid := testutil.MustCreateTask(t, srv, pid, "Referenced Task")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{
			"title":   "With References",
			"content": "See TASK-" + tid + " for details.",
		}, testutil.DemoUserID)
	var page map[string]interface{}
	testutil.DecodeJSON(t, cr, &page)
	pageID := page["id"].(string)

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/references/rebuild",
		nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var refs []map[string]interface{}
	testutil.DecodeJSON(t, resp, &refs)
	if len(refs) != 1 {
		t.Errorf("expected 1 reference, got %d", len(refs))
	}
	if refs[0]["taskId"] != tid {
		t.Errorf("taskId = %v, want %v", refs[0]["taskId"], tid)
	}
}

func TestListRevisions_Empty(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")

	cr := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "No Revisions"}, testutil.DemoUserID)
	var p map[string]interface{}
	testutil.DecodeJSON(t, cr, &p)
	pageID := p["id"].(string)

	resp := testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/"+pageID+"/revisions", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var revs []interface{}
	testutil.DecodeJSON(t, resp, &revs)
	if len(revs) != 0 {
		t.Errorf("expected 0 revisions before publish, got %d", len(revs))
	}
}

func TestDeletePage_OK(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	pageID := mustCreatePageID(t, srv, pid, "Delete Me", "")

	resp := testutil.Do(t, srv, http.MethodDelete, "/api/v1/pages/"+pageID, nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusNoContent)
	_ = resp.Body.Close()

	// Subsequent GET should return 404.
	resp = testutil.Do(t, srv, http.MethodGet, "/api/v1/pages/"+pageID, nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusNotFound)
	_ = resp.Body.Close()
}

func TestDeletePage_NotFound(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)

	resp := testutil.Do(t, srv, http.MethodDelete,
		"/api/v1/pages/00000000-0000-0000-0000-000000000000", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusNotFound)

	var e map[string]interface{}
	testutil.DecodeJSON(t, resp, &e)
	if e["code"] != "PAGE_NOT_FOUND" {
		t.Errorf("code = %v, want PAGE_NOT_FOUND", e["code"])
	}
}

func TestListReferences_OK(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	tid := testutil.MustCreateTask(t, srv, pid, "Referenced Task")

	// Create a page that references the task.
	pageID := mustCreatePageID(t, srv, pid, "Refs Page", "See TASK-"+tid+" for details.")

	// Rebuild references.
	rb := testutil.Do(t, srv, http.MethodPost,
		"/api/v1/pages/"+pageID+"/references/rebuild",
		map[string]string{}, testutil.DemoUserID)
	testutil.AssertStatus(t, rb, http.StatusOK)
	_ = rb.Body.Close()

	// List references — should contain the task.
	resp := testutil.Do(t, srv, http.MethodGet,
		"/api/v1/pages/"+pageID+"/references", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)

	var refs []interface{}
	testutil.DecodeJSON(t, resp, &refs)
	if len(refs) == 0 {
		t.Error("expected at least one reference after rebuild")
	}
}

func TestListRevisions_NonEmpty(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	pageID := mustCreatePageID(t, srv, pid, "Published Page", "Content v1")

	// Publish creates a revision.
	pub := testutil.Do(t, srv, http.MethodPost,
		"/api/v1/pages/"+pageID+"/publish",
		map[string]string{}, testutil.DemoUserID)
	testutil.AssertStatus(t, pub, http.StatusOK)
	_ = pub.Body.Close()

	resp := testutil.Do(t, srv, http.MethodGet,
		"/api/v1/pages/"+pageID+"/revisions", nil, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)

	var revs []interface{}
	testutil.DecodeJSON(t, resp, &revs)
	if len(revs) < 1 {
		t.Errorf("expected at least 1 revision after publish, got %d", len(revs))
	}
}

// xssPayload exercises script injection, event handlers, javascript: links and
// external/data image sources through the page lifecycle. These tests are
// DB-gated (skip without TEST_DATABASE_URL).
const xssPayload = "= Title\n\n<script>alert(1)</script>\n\nimage::https://evil.test/p.png[x]\n\nlink:javascript:alert(1)[click]\n"

func assertSafe(t *testing.T, html string) {
	t.Helper()
	if strings.Contains(html, "<script") {
		t.Errorf("live <script> present: %s", html)
	}
	if strings.Contains(html, `href="javascript:`) {
		t.Errorf("javascript href present: %s", html)
	}
	if strings.Contains(html, "evil.test") {
		t.Errorf("external image src present: %s", html)
	}
	if strings.Contains(html, " onerror") || strings.Contains(html, " onclick") {
		t.Errorf("event handler present: %s", html)
	}
}

func TestCreatePage_SanitizesXSS(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/projects/"+pid+"/pages",
		map[string]string{"title": "Evil", "content": xssPayload}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusCreated)
	var p map[string]interface{}
	testutil.DecodeJSON(t, resp, &p)
	assertSafe(t, p["renderedHtml"].(string))
}

func TestUpdateAndPublishPage_SanitizesXSS(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	pageID := mustCreatePageID(t, srv, pid, "Evil2", "= ok\n")

	up := testutil.Do(t, srv, http.MethodPatch, "/api/v1/pages/"+pageID,
		map[string]string{"content": xssPayload}, testutil.DemoUserID)
	testutil.AssertStatus(t, up, http.StatusOK)
	var upd map[string]interface{}
	testutil.DecodeJSON(t, up, &upd)
	assertSafe(t, upd["renderedHtml"].(string))

	pub := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/publish",
		map[string]string{"message": "m"}, testutil.DemoUserID)
	testutil.AssertStatus(t, pub, http.StatusOK)
	var pp map[string]interface{}
	testutil.DecodeJSON(t, pub, &pp)
	assertSafe(t, pp["renderedHtml"].(string))
}

func TestRenderPreview_SanitizesXSS(t *testing.T) {
	db := testutil.NewTestDB(t)
	srv := testutil.NewTestServer(t, db)
	pid := testutil.MustCreateProject(t, srv, "P")
	pageID := mustCreatePageID(t, srv, pid, "Evil3", "= ok\n")

	resp := testutil.Do(t, srv, http.MethodPost, "/api/v1/pages/"+pageID+"/render-preview",
		map[string]string{"content": xssPayload}, testutil.DemoUserID)
	testutil.AssertStatus(t, resp, http.StatusOK)
	var result map[string]interface{}
	testutil.DecodeJSON(t, resp, &result)
	assertSafe(t, result["html"].(string))
}
