-- Baseline schema — the whole database as of the squash (2026-08-03).
--
-- This replaces migrations 001–039, which were removed. Their per-change
-- rationale is not lost, only moved: read it with
--   git log --follow -- octbase-api/migrations/
-- against the commit that introduced this file, or check out its parent.
--
-- Generated by dumping a database with 001–039 applied in order, so it is the
-- schema those 39 migrations actually produced rather than a hand-transcription
-- of them.
--
-- Names are deliberately unqualified: RunMigrations executes this through the
-- pgx driver with whatever search_path the connection carries, and the Go
-- handler tests pin that to a throwaway tbtest_<uuid> schema
-- (internal/testutil.NewTestDB). Qualifying these as public.* would create one
-- shared set of tables and break test isolation.
--
-- EXISTING DEPLOYMENTS ARE NOT MIGRATED BY THIS FILE. An instance already at
-- schema_migrations version 38/39 has this schema; it needs its version stamped
-- down to 1 (`migrate force 1`) so its live version matches what is on disk.
-- Until then /api/v1/health reports degraded, because main.go compares the DB
-- version against LatestMigrationVersion(migrations). See docs/operations.md.

-- Serializes concurrent test-schema migration runs, which would otherwise
-- race on CREATE EXTENSION IF NOT EXISTS (carried over from migration 022).
SELECT pg_advisory_xact_lock(422202600);
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE IF NOT EXISTS activity_entries (
    id text NOT NULL,
    project_id text NOT NULL,
    task_id text,
    actor_user_id text NOT NULL,
    type text NOT NULL,
    message text NOT NULL,
    payload_json text DEFAULT '{}'::text NOT NULL,
    created_at text NOT NULL,
    release_id text,
    sprint_id text,
    target_deleted boolean DEFAULT false NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id text NOT NULL,
    actor_user_id text DEFAULT ''::text NOT NULL,
    action text NOT NULL,
    target_type text DEFAULT ''::text NOT NULL,
    target_id text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    ip_address text DEFAULT ''::text NOT NULL,
    user_agent text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS board_columns (
    id text NOT NULL,
    board_id text NOT NULL,
    name text NOT NULL,
    status text DEFAULT 'PLANNED'::text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS board_external_columns (
    id text NOT NULL,
    board_id text NOT NULL,
    source_column_id text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS boards (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    is_default integer DEFAULT 0 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    min_columns integer DEFAULT 1 NOT NULL,
    max_columns integer DEFAULT 10 NOT NULL,
    is_sprint_board integer DEFAULT 0 NOT NULL,
    sprint_id text,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS branch_references (
    id text NOT NULL,
    task_id text NOT NULL,
    repository_id text NOT NULL,
    branch_name text NOT NULL,
    branch_type text DEFAULT 'feature'::text NOT NULL,
    created_at text NOT NULL,
    pr_status text,
    pr_url text,
    pr_number integer
);

CREATE TABLE IF NOT EXISTS invitations (
    id text NOT NULL,
    email text NOT NULL,
    project_id text,
    role text DEFAULT 'DEVELOPER'::text NOT NULL,
    token_hash text NOT NULL,
    invited_by text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    accepted_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS memberships (
    id text NOT NULL,
    project_id text NOT NULL,
    user_id text NOT NULL,
    role text DEFAULT 'DEVELOPER'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    assigned_by_user_id text
);

CREATE TABLE IF NOT EXISTS mfa_credentials (
    user_id text NOT NULL,
    encrypted_secret text NOT NULL,
    confirmed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_totp_step bigint DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS mfa_recovery_codes (
    id text NOT NULL,
    user_id text NOT NULL,
    code_hash text NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id text NOT NULL,
    kind text NOT NULL,
    in_app boolean DEFAULT true NOT NULL,
    email boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
    id text NOT NULL,
    user_id text NOT NULL,
    kind text NOT NULL,
    project_id text,
    task_id text,
    page_id text,
    message text NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_states (
    state text NOT NULL,
    provider text NOT NULL,
    repository_id text NOT NULL,
    user_id text NOT NULL,
    created_at text NOT NULL,
    expires_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS page_revisions (
    id text NOT NULL,
    page_id text NOT NULL,
    content text NOT NULL,
    message text DEFAULT ''::text NOT NULL,
    author_id text NOT NULL,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS page_task_references (
    id text NOT NULL,
    page_id text NOT NULL,
    task_id text NOT NULL,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS pages (
    id text NOT NULL,
    project_id text NOT NULL,
    parent_page_id text,
    title text NOT NULL,
    slug text NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    rendered_html text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'DRAFT'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    external_ref text
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    token_hash text NOT NULL,
    user_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS project_priorities (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    rank integer DEFAULT 0 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS project_task_counters (
    project_id text NOT NULL,
    last_seq integer DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
    id text NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    visibility text DEFAULT 'PRIVATE'::text NOT NULL,
    status text DEFAULT 'ACTIVE'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    created_by_user_id text,
    abbreviation character varying(10) DEFAULT ''::character varying NOT NULL,
    theme_enabled boolean DEFAULT false NOT NULL,
    initiative_enabled boolean DEFAULT false NOT NULL,
    estimation_unit text DEFAULT 'NONE'::text NOT NULL,
    board_lane_limit integer DEFAULT 20 NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id text NOT NULL,
    user_id text NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    rotated_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS releases (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    goal text DEFAULT ''::text NOT NULL,
    due_date text,
    status text DEFAULT 'PLANNED'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS repository_connections (
    id text NOT NULL,
    project_id text NOT NULL,
    provider text DEFAULT 'FAKE_GITLAB'::text NOT NULL,
    display_name text NOT NULL,
    repository_url text NOT NULL,
    default_branch text DEFAULT 'main'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    auto_close_on_merge boolean DEFAULT false NOT NULL,
    access_token_enc text,
    api_base_url text,
    auth_kind text DEFAULT 'PAT'::text NOT NULL,
    refresh_token_enc text,
    token_expires_at text,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS sprints (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    goal text DEFAULT ''::text NOT NULL,
    start_date text,
    end_date text,
    status text DEFAULT 'PLANNED'::text NOT NULL,
    release_id text,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    committed_count integer DEFAULT 0 NOT NULL,
    completed_count integer DEFAULT 0 NOT NULL,
    committed_estimate numeric(10,2),
    completed_estimate numeric(10,2),
    estimate_unit text
);

CREATE TABLE IF NOT EXISTS task_attachments (
    id text NOT NULL,
    task_id text NOT NULL,
    filename text NOT NULL,
    content_type text DEFAULT ''::text NOT NULL,
    size_bytes integer DEFAULT 0 NOT NULL,
    external_url text DEFAULT ''::text NOT NULL,
    created_at text NOT NULL,
    storage_key text,
    uploaded_by text
);

CREATE TABLE IF NOT EXISTS task_categories (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    color text DEFAULT 'gray'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS task_comments (
    id text NOT NULL,
    task_id text NOT NULL,
    author_id text NOT NULL,
    text text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    parent_id text,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS task_links (
    id text NOT NULL,
    task_id text NOT NULL,
    url text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS task_relations (
    id text NOT NULL,
    source_task_id text NOT NULL,
    target_task_id text NOT NULL,
    relation_type text DEFAULT 'RELATES_TO'::text NOT NULL,
    created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS task_templates (
    id text NOT NULL,
    project_id text NOT NULL,
    name text NOT NULL,
    title_template text DEFAULT ''::text NOT NULL,
    description_template text DEFAULT ''::text NOT NULL,
    task_type text DEFAULT 'TASK'::text NOT NULL,
    priority text DEFAULT 'MEDIUM'::text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id text NOT NULL,
    project_id text NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    task_type text DEFAULT 'TASK'::text NOT NULL,
    status text DEFAULT 'PLANNED'::text NOT NULL,
    priority text DEFAULT 'MEDIUM'::text NOT NULL,
    assignee_id text,
    reporter_id text,
    reviewer_id text,
    release_id text,
    board_column_id text,
    board_rank integer DEFAULT 1000 NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    seq_number integer,
    external_ref text,
    sprint_id text,
    due_date text,
    pinned boolean DEFAULT false NOT NULL,
    done_at text,
    parent_id text,
    story_points integer,
    estimate_hours numeric(7,2)
);

CREATE TABLE IF NOT EXISTS user_preferences (
    user_id text NOT NULL,
    language text DEFAULT 'en'::text NOT NULL,
    theme text DEFAULT 'system'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    terminology text DEFAULT 'AGILE'::text NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id text NOT NULL,
    email text NOT NULL,
    display_name text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL,
    password_hash text,
    is_active boolean DEFAULT true NOT NULL,
    is_admin boolean DEFAULT false NOT NULL,
    global_role text DEFAULT 'USER'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    last_login_at timestamp with time zone,
    mfa_enabled boolean DEFAULT false NOT NULL,
    avatar bytea,
    avatar_content_type text,
    avatar_updated_at text
);

ALTER TABLE ONLY activity_entries
    ADD CONSTRAINT activity_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY board_columns
    ADD CONSTRAINT board_columns_pkey PRIMARY KEY (id);

ALTER TABLE ONLY board_external_columns
    ADD CONSTRAINT board_external_columns_board_id_source_column_id_key UNIQUE (board_id, source_column_id);

ALTER TABLE ONLY board_external_columns
    ADD CONSTRAINT board_external_columns_pkey PRIMARY KEY (id);

ALTER TABLE ONLY boards
    ADD CONSTRAINT boards_pkey PRIMARY KEY (id);

ALTER TABLE ONLY branch_references
    ADD CONSTRAINT branch_references_pkey PRIMARY KEY (id);

ALTER TABLE ONLY invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY invitations
    ADD CONSTRAINT invitations_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);

ALTER TABLE ONLY memberships
    ADD CONSTRAINT memberships_project_id_user_id_key UNIQUE (project_id, user_id);

ALTER TABLE ONLY mfa_credentials
    ADD CONSTRAINT mfa_credentials_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY mfa_recovery_codes
    ADD CONSTRAINT mfa_recovery_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id, kind);

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY oauth_states
    ADD CONSTRAINT oauth_states_pkey PRIMARY KEY (state);

ALTER TABLE ONLY page_revisions
    ADD CONSTRAINT page_revisions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY page_task_references
    ADD CONSTRAINT page_task_references_page_id_task_id_key UNIQUE (page_id, task_id);

ALTER TABLE ONLY page_task_references
    ADD CONSTRAINT page_task_references_pkey PRIMARY KEY (id);

ALTER TABLE ONLY pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (token_hash);

ALTER TABLE ONLY project_priorities
    ADD CONSTRAINT project_priorities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY project_priorities
    ADD CONSTRAINT project_priorities_project_id_name_key UNIQUE (project_id, name);

ALTER TABLE ONLY project_task_counters
    ADD CONSTRAINT project_task_counters_pkey PRIMARY KEY (project_id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT projects_slug_key UNIQUE (slug);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);

ALTER TABLE ONLY releases
    ADD CONSTRAINT releases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY repository_connections
    ADD CONSTRAINT repository_connections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY sprints
    ADD CONSTRAINT sprints_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_attachments
    ADD CONSTRAINT task_attachments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_categories
    ADD CONSTRAINT task_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_comments
    ADD CONSTRAINT task_comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_links
    ADD CONSTRAINT task_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_relations
    ADD CONSTRAINT task_relations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY task_templates
    ADD CONSTRAINT task_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY tasks
    ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX IF NOT EXISTS idx_activity_project ON activity_entries USING btree (project_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activity_release ON activity_entries USING btree (release_id);

CREATE INDEX IF NOT EXISTS idx_activity_sprint ON activity_entries USING btree (sprint_id);

CREATE INDEX IF NOT EXISTS idx_activity_task ON activity_entries USING btree (task_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs USING btree (action);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs USING btree (actor_user_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs USING btree (created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_board_columns_board_status ON board_columns USING btree (board_id, status);

CREATE INDEX IF NOT EXISTS idx_board_external_columns_board ON board_external_columns USING btree (board_id);

CREATE INDEX IF NOT EXISTS idx_boards_project ON boards USING btree (project_id);

CREATE INDEX IF NOT EXISTS idx_boards_sprint_id ON boards USING btree (sprint_id);

CREATE INDEX IF NOT EXISTS idx_branch_refs_task ON branch_references USING btree (task_id);

CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_mfa_recovery_codes_user ON mfa_recovery_codes USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications USING btree (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_page_refs_page ON page_task_references USING btree (page_id);

CREATE INDEX IF NOT EXISTS idx_page_refs_task ON page_task_references USING btree (task_id);

CREATE INDEX IF NOT EXISTS idx_page_revisions_author ON page_revisions USING btree (author_id);

CREATE INDEX IF NOT EXISTS idx_page_revisions_page_created ON page_revisions USING btree (page_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_pages_content_trgm ON pages USING gin (content public.gin_trgm_ops);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pages_project_slug ON pages USING btree (project_id, slug);

CREATE INDEX IF NOT EXISTS idx_pages_title_trgm ON pages USING gin (title public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user ON password_reset_tokens USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_project_priorities_project ON project_priorities USING btree (project_id);

CREATE INDEX IF NOT EXISTS idx_projects_name_trgm ON projects USING gin (name public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_releases_project ON releases USING btree (project_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sprints_one_active ON sprints USING btree (project_id) WHERE (status = 'ACTIVE'::text);

CREATE INDEX IF NOT EXISTS idx_sprints_project_status ON sprints USING btree (project_id, status);

CREATE INDEX IF NOT EXISTS idx_task_attachments_task_created ON task_attachments USING btree (task_id, created_at);

CREATE INDEX IF NOT EXISTS idx_task_attachments_uploaded_by ON task_attachments USING btree (uploaded_by) WHERE (uploaded_by IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_task_comments_parent_id ON task_comments USING btree (parent_id);

CREATE INDEX IF NOT EXISTS idx_task_comments_task_created ON task_comments USING btree (task_id, created_at);

CREATE INDEX IF NOT EXISTS idx_task_links_task_created ON task_links USING btree (task_id, created_at);

CREATE INDEX IF NOT EXISTS idx_task_relations_source_type ON task_relations USING btree (source_task_id, relation_type);

CREATE INDEX IF NOT EXISTS idx_task_relations_target ON task_relations USING btree (target_task_id);

CREATE INDEX IF NOT EXISTS idx_tasks_assignee_id ON tasks USING btree (assignee_id);

CREATE INDEX IF NOT EXISTS idx_tasks_board_column ON tasks USING btree (board_column_id);

CREATE INDEX IF NOT EXISTS idx_tasks_description_trgm ON tasks USING gin (description public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_tasks_done_at ON tasks USING btree (done_at);

CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks USING btree (due_date);

CREATE INDEX IF NOT EXISTS idx_tasks_external_ref ON tasks USING btree (external_ref);

CREATE INDEX IF NOT EXISTS idx_tasks_parent_id ON tasks USING btree (parent_id);

CREATE INDEX IF NOT EXISTS idx_tasks_project_created ON tasks USING btree (project_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON tasks USING btree (project_id);

CREATE INDEX IF NOT EXISTS idx_tasks_release_id ON tasks USING btree (release_id);

CREATE INDEX IF NOT EXISTS idx_tasks_sprint_id ON tasks USING btree (sprint_id);

CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks USING btree (status);

CREATE INDEX IF NOT EXISTS idx_tasks_title_trgm ON tasks USING gin (title public.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_users_global_role ON users USING btree (global_role);

ALTER TABLE ONLY board_columns
    ADD CONSTRAINT board_columns_board_id_fkey FOREIGN KEY (board_id) REFERENCES boards(id);

ALTER TABLE ONLY board_external_columns
    ADD CONSTRAINT board_external_columns_board_id_fkey FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE;

ALTER TABLE ONLY board_external_columns
    ADD CONSTRAINT board_external_columns_source_column_id_fkey FOREIGN KEY (source_column_id) REFERENCES board_columns(id) ON DELETE CASCADE;

ALTER TABLE ONLY boards
    ADD CONSTRAINT boards_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY boards
    ADD CONSTRAINT boards_sprint_id_fkey FOREIGN KEY (sprint_id) REFERENCES sprints(id) ON DELETE SET NULL;

ALTER TABLE ONLY branch_references
    ADD CONSTRAINT branch_references_repository_id_fkey FOREIGN KEY (repository_id) REFERENCES repository_connections(id);

ALTER TABLE ONLY branch_references
    ADD CONSTRAINT branch_references_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY activity_entries
    ADD CONSTRAINT fk_activity_entries_project FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY activity_entries
    ADD CONSTRAINT fk_activity_entries_release FOREIGN KEY (release_id) REFERENCES releases(id);

ALTER TABLE ONLY activity_entries
    ADD CONSTRAINT fk_activity_entries_sprint FOREIGN KEY (sprint_id) REFERENCES sprints(id);

ALTER TABLE ONLY activity_entries
    ADD CONSTRAINT fk_activity_entries_task FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY invitations
    ADD CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES users(id);

ALTER TABLE ONLY invitations
    ADD CONSTRAINT invitations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY memberships
    ADD CONSTRAINT memberships_assigned_by_user_id_fkey FOREIGN KEY (assigned_by_user_id) REFERENCES users(id);

ALTER TABLE ONLY memberships
    ADD CONSTRAINT memberships_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY memberships
    ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY mfa_credentials
    ADD CONSTRAINT mfa_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY mfa_recovery_codes
    ADD CONSTRAINT mfa_recovery_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY notification_preferences
    ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_page_id_fkey FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE;

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE;

ALTER TABLE ONLY notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY oauth_states
    ADD CONSTRAINT oauth_states_repository_id_fkey FOREIGN KEY (repository_id) REFERENCES repository_connections(id) ON DELETE CASCADE;

ALTER TABLE ONLY page_revisions
    ADD CONSTRAINT page_revisions_page_id_fkey FOREIGN KEY (page_id) REFERENCES pages(id);

ALTER TABLE ONLY page_task_references
    ADD CONSTRAINT page_task_references_page_id_fkey FOREIGN KEY (page_id) REFERENCES pages(id);

ALTER TABLE ONLY page_task_references
    ADD CONSTRAINT page_task_references_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY pages
    ADD CONSTRAINT pages_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY project_priorities
    ADD CONSTRAINT project_priorities_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY project_task_counters
    ADD CONSTRAINT project_task_counters_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;

ALTER TABLE ONLY projects
    ADD CONSTRAINT projects_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE ONLY releases
    ADD CONSTRAINT releases_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY repository_connections
    ADD CONSTRAINT repository_connections_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY sprints
    ADD CONSTRAINT sprints_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY sprints
    ADD CONSTRAINT sprints_release_id_fkey FOREIGN KEY (release_id) REFERENCES releases(id) ON DELETE SET NULL;

ALTER TABLE ONLY task_attachments
    ADD CONSTRAINT task_attachments_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY task_attachments
    ADD CONSTRAINT task_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users(id);

ALTER TABLE ONLY task_categories
    ADD CONSTRAINT task_categories_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY task_comments
    ADD CONSTRAINT task_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES task_comments(id) ON DELETE CASCADE;

ALTER TABLE ONLY task_comments
    ADD CONSTRAINT task_comments_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY task_links
    ADD CONSTRAINT task_links_task_id_fkey FOREIGN KEY (task_id) REFERENCES tasks(id);

ALTER TABLE ONLY task_relations
    ADD CONSTRAINT task_relations_source_task_id_fkey FOREIGN KEY (source_task_id) REFERENCES tasks(id);

ALTER TABLE ONLY task_relations
    ADD CONSTRAINT task_relations_target_task_id_fkey FOREIGN KEY (target_task_id) REFERENCES tasks(id);

ALTER TABLE ONLY task_templates
    ADD CONSTRAINT task_templates_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY tasks
    ADD CONSTRAINT tasks_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES tasks(id);

ALTER TABLE ONLY tasks
    ADD CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY tasks
    ADD CONSTRAINT tasks_sprint_id_fkey FOREIGN KEY (sprint_id) REFERENCES sprints(id) ON DELETE SET NULL;

ALTER TABLE ONLY user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
