-- Retire the `release_due` notification kind.
--
-- It was declared, given a subject line and a preference toggle, and never
-- emitted by anything: there is no scheduler, and a release carries no owner,
-- so "a release you own is due" was not expressible. Retired rather than
-- implemented on 2026-07-31.
--
-- The stored rows are preferences for a notification that has never been sent
-- and can no longer be sent. Leaving them would keep a dead setting alive in
-- every GET /users/me/notification-preferences response, which is exactly the
-- confusion this change removes.
DELETE FROM notification_preferences WHERE kind = 'release_due';
