-- Board lane limit: how many cards a board lane renders before the rest are
-- loaded on demand.
--
-- The value is a per-project display setting, not a data constraint: every task
-- stays on its lane and every count badge keeps reporting the full lane size.
-- Only the number of cards drawn at once is capped, so a Done lane with 800
-- finished tasks stops building 800 DOM nodes on every repaint.
--
-- 20 is the default, matching the value the request asked for. 0 means "no
-- limit" (draw the whole lane), which is the pre-38 behaviour and therefore the
-- escape hatch for anyone who wants it back. The accepted range is enforced in
-- the application layer (see ValidBoardLaneLimit), matching how visibility,
-- status and estimation_unit are already stored as plain columns without CHECK
-- constraints.
ALTER TABLE projects ADD COLUMN IF NOT EXISTS board_lane_limit INT NOT NULL DEFAULT 20;
